package main

func main() {
	// packages()
	// imports()
	// exportedNames()
	// functions()
	// functionsContinued()
	// multipleResults()
	// namedReturns()
	// variables()
	// variableInitializers()
	// shortVariableDeclaration()
	// basicTypes()
	// zeroValues()
	// typeConversion()
	// typeInference()
	// constants()
	// numericConstants()
	// forLoops()
	// forContinued()
	// foreverLoop()
	// ifStatement()
	// ifWithShortStatement()
	// ifAndElse()
	// loopsAndFunctionsExercise()
	// switchInstructions()
	// switchEvaluationOrder()
	// switchWithNoCondition()
	// deferStatement()
	deferStacking()
}
